### ISSUE TITLE
Something wrong with dataset 

### ISSUE THREAD

**Issue by Sasukiii** [ipl-uw/AIC23_Track1_UWIPL_ETRI#3]
When I tried to train the torchreid module, I found the following error in the cp command in the train-reid.sh file:
log/aicity_imagenet_pretrained/model/model.pth.tar-60
This directory does not exist, nor does the file to be copied exist, please update the project or provide the corresponding file, thank you very much.

**Comment by Sasukiii** [comment]
The error:
cp: 无法获取'log/aicity_imagenet_pretrained/model/model.pth.tar-60' 的文件状态(stat): 没有那个文件或目录

**Comment by Sasukiii** [comment]
And I've got aicity chanllenge's dataset, but I still haven't generated the corresponding file in the module before re-id.

**Comment by hsiangwei0903** [comment]
Hi @Sasukiii, can you share more error message with us so that we can try to debug for you?
The training script contain the training part and also copying the model to the new path.
It seems that the error is reported because the model does not exist, which might casued by the failure of training.
Did you successfully finished the ReID model training?

**Comment by Sasukiii** [comment]
Hi @hsiangwei0903 ,Thank you very much for your reply. Now I have proceeded to the Train Synthetic ReID Model. The preparation of data set in step 0 has been completed, but after running the command "bash 2_train_reid.sh" in step 1, the following error occurs:
ImportError:  cannot import name 'Dataset' from 'torchreid.data.datasets'  (/data/zyh/AIC23_Track1_UWIPL_ETRI/deep-person-reid/torchreid/data/datasets/__init__.py)
Said it did not "log/aicity_imagenet_pretrained/model/model. PTH. Tar - 60" files under this path, even without the "log" folder, it makes me very sad, I hope you can give me help.

**Comment by hsiangwei0903** [comment]
It seems that the code uploading process was interrupted when we upload our code before. That is why the 'Dataset' can not be imported. We apologize for the inconvenience and I just re-upload the code. You might need to clone the code again before you re-run the code on your side. 

BTW, if you just want to re-produce our result, it is suggested to skip the model training and directly download our pre-trained ReID weight so that the exact same result can be re-produce. We did not train another ReID model for the second time so we are not sure if training the model again can still produce the exact same tracking result as our current model, since all the parameter fine-tuning is based on the model trained by us.

Please try to run the code again and let us know if any question!
