### ISSUE TITLE
Hope to reply

### ISSUE THREAD

**Issue by Sasukiii** [ipl-uw/AIC23_Track1_UWIPL_ETRI#6]
When running aic_track.py, why is cpu still used for testing even though the default device is gpu? Even if I use the display command to specify the GPU run, it is still on the cpu test, hope you can reply as soon as possible, thank you!

**Comment by hsiangwei0903** [comment]
The tracking is performed on CPU. Only the detection and embedding model training/inference are performed on GPU using PyTorch framework. Please try to run our code on the CPU, thank you.

**Comment by Sasukiii** [comment]
Is it possible to run the tracking module on the GPU as well, and where do I need to make changes to the code?

**Comment by hsiangwei0903** [comment]
You need to modify most of the code since our current code is based on packages like numpy, sklearn, which can not be accelerated using GPU (based on my understanding). You might need to use some other packages that can be supported with GPU acceleration and rewrite the codebase in order to run them on GPU.

**Comment by Sasukiii** [comment]
Thank you
